import "server-only";

import {
  buildIosContentsJson,
  buildWebManifest,
  filesForKinds,
  type AppAssetKind,
} from "./catalog";
import { buildAdaptiveBackground, resizeIcon } from "./raster";

export type BuiltAssetFile = {
  path: string;
  label: string;
  buffer: Buffer;
  mediaType: "image/png" | "image/svg+xml" | "application/json" | "text/plain";
};

export async function buildAssetFiles(args: {
  masterPng: Buffer;
  idleSvg: string;
  kinds: AppAssetKind[];
  accent: string;
  name: string;
  tagline: string;
}): Promise<BuiltAssetFile[]> {
  const specs = filesForKinds(args.kinds);
  const out: BuiltAssetFile[] = [];

  for (const spec of specs) {
    if (spec.path.endsWith(".svg")) {
      out.push({
        path: spec.path,
        label: spec.label,
        buffer: Buffer.from(args.idleSvg, "utf8"),
        mediaType: "image/svg+xml",
      });
      continue;
    }

    if (spec.path.includes("adaptive_background")) {
      out.push({
        path: spec.path,
        label: spec.label,
        buffer: await buildAdaptiveBackground(
          args.masterPng,
          args.accent,
          spec.width
        ),
        mediaType: "image/png",
      });
      continue;
    }

    out.push({
      path: spec.path,
      label: spec.label,
      buffer: await resizeIcon(args.masterPng, spec),
      mediaType: "image/png",
    });
  }

  if (args.kinds.includes("pwa")) {
    out.push({
      path: "pwa/site.webmanifest",
      label: "PWA web manifest",
      buffer: Buffer.from(
        buildWebManifest({
          name: args.name,
          shortName: args.name,
          themeColor: args.accent.startsWith("#") ? args.accent : "#6366f1",
          backgroundColor: "#ffffff",
        }),
        "utf8"
      ),
      mediaType: "application/json",
    });
  }

  if (args.kinds.includes("app_icon")) {
    out.push({
      path: "ios/Contents.json",
      label: "Xcode AppIcon Contents.json",
      buffer: Buffer.from(buildIosContentsJson(), "utf8"),
      mediaType: "application/json",
    });
  }

  const readme = [
    `# ${args.name} — App assets`,
    "",
    args.tagline,
    "",
    "Generated by MascotAI. Each file is labeled in this pack.",
    "",
    "Included:",
    ...out.map((f) => `- ${f.path} — ${f.label}`),
  ].join("\n");

  out.push({
    path: "README.txt",
    label: "Pack readme",
    buffer: Buffer.from(readme, "utf8"),
    mediaType: "text/plain",
  });

  return out;
}
